sudo: false
language: php

php:
  - 7.1
  - 7.2

env:
  global:
  - WP_VERSION=latest WP_MULTISITE=0

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - develop
    - "/\\d+\\.\\d+\\.\\d+?.*/"

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor

install:
  - nvm install 8
  - npm install
  - composer install

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - composer test

before_deploy:
  - npm run build
  - npm run zip
  - ls -la snow-monkey-forms.zip
  - export RELEASE_FILE=$(ls snow-monkey-forms.zip)
