dist: trusty
sudo: false
language: php
php:
- 7.2
- 7.3
env:
  global:
  - WP_VERSION=latest WP_MULTISITE=0
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
cache:
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
install:
- nvm install 8
- npm install
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
before_deploy:
- npm run build
- npm run zip
- ls -la snow-monkey-forms.zip
- export RELEASE_FILE=$(ls snow-monkey-forms.zip)
deploy:
  provider: releases
  api_key:
    secure: iwlxu8IQbf9D/hCH0QCkutVDu8Uk9qfwoaipks6COGmyi9Eu2v3x1Sq1LPBRH7WGydPq4+n2LvydBgCrx/1jKfb2aGKiiuqOu+T7FI8rtapjtgTle+QdWFUy3xX9Fc0b5vxm8/PmScLzHUkkROGigG5RkWAWUtla7kLtWSmczKu65W8hVZvsSqN2GW0RZkLEQ/OAXfoazsy7A0Dp1aDGPhlGtVtESzqKuM3ouhIu+Ks2+xM023b2uNVoIQPflDA2thNDOSHsSngYSutriLFPn43dPqHwhANfa+Q/aRSUHyultM/cP0U0X+/V8GVAEJbrW0F3Cwp6X9Yjt3dKvecZ4kFvD+N1zlh/Te6jPEPSIroXxZ34s8QIzGG3f88po4ROqPo9pIrXFNJiyFP7PR/V94IPWwoRTTgolC4bjP/8zuOJdjsUAdTH3ybc5XOh5VLhnhujlpJ7rKjr46x2P/RWP2AN9shGPMEU4XozD5NTWjeW+u/1l9QbjWfiD0sLC8Fp6CkgXkz2vrojBhUDpe4sg5N6SK+Ne/7BNrXffH7f8mabVaJKeUw5URNOu7NDrS4WnQ3EsjlWm0HYDyRYGkrJxp1tsOO4OG0YlAu6S5m+Gp5Wc0l4JkXyHPCFV9YOCisrHxOntuzdV4wxc+p5KmNkiJLzUWyGk1csdnelM/beTxQ=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    php: 7.3
    repo: inc2734/snow-monkey-forms
